{% set name = "cxxfilt" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7df6464ba5e8efbf0d8974c0b2c78b32546676f06059a83515dbdfa559b34214

build:
  number: 5
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cxxfilt

about:
  home: https://github.com/afg984/python-cxxfilt
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to c++filt / abi::__cxa_demangle
  doc_url: https://pypi.org/project/cxxfilt/
  dev_url: https://github.com/afq984/python-cxxfilt

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
